services:
  db:
    image: postgres:14.1
    env_file:
      ./db/.env
    volumes:
      - /Users/barely/coding/PyCharmProjects/vinylin_rest/db/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"

  drf_vinylin:
    build: vinylin/
    env_file:
      ./vinylin/.env
    volumes:
      - /Users/barely/coding/PyCharmProjects/vinylin_rest/vinylin:/usr/src/vinylin/
    tty: True
    ports:
      - "8000:8000"
    depends_on:
      - db
