# Generated by Django 3.2.13 on 2022-05-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['pk']},
        ),
    ]
