# Generated by Django 3.2.13 on 2022-05-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0002_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
    ]
