# Generated by Django 3.2.13 on 2022-05-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0004_alter_vinyl_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='vinyl.country'),
        ),
    ]
