# Generated by Django 3.2.13 on 2022-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0006_alter_vinyl_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylStock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vinyl.vinyl',),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
