# Generated by Django 3.2.13 on 2022-05-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_tags'),
        ('orders', '0002_remove_cart_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
