# Generated by Django 3.2.13 on 2022-05-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_discount_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
