# Generated by Django 3.2.13 on 2022-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
